# Generated by Django 4.2.7 on 2023-12-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='team',
            field=models.ForeignKey(default=15.143939393939394, on_delete=django.db.models.deletion.CASCADE, to='user_app.team'),
            preserve_default=False,
        ),
    ]
