# Generated by Django 4.2.7 on 2023-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='team_strength',
            field=models.IntegerField(null=True),
        ),
    ]
