# Generated by Django 4.2.7 on 2023-12-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_leaderboard_team_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='number_of_wins',
            field=models.IntegerField(default=0),
        ),
    ]
