# Generated by Django 4.2.7 on 2023-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_leaderboard_number_of_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='aggregate_score_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='win_ratio',
            field=models.FloatField(default=0),
        ),
    ]
