# Generated by Django 4.2.7 on 2023-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_leaderboard_aggregate_score_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=30)),
                ('reward_image', models.ImageField(null=True, upload_to='reward_images/')),
                ('reward_points', models.IntegerField(default=0)),
            ],
        ),
    ]
