# Generated by Django 4.2.7 on 2023-12-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('stripe_charge_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=55)),
                ('player_skill', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional')], default='Beginner', max_length=20)),
                ('player_pic', models.ImageField(null=True, upload_to='player_image/')),
                ('player_position', models.CharField(max_length=10)),
                ('invitation_pending', models.BooleanField(default=False)),
                ('player_longitude', models.FloatField(null=True)),
                ('player_latitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=55)),
                ('team_skill', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional')], default='Beginner', max_length=20)),
                ('team_pic', models.ImageField(null=True, upload_to='team_image/')),
                ('team_strength', models.IntegerField()),
                ('team_longitude', models.FloatField(null=True)),
                ('team_latitude', models.FloatField(null=True)),
                ('team_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='players', to='user_app.team'),
        ),
        migrations.CreateModel(
            name='MatchInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('receiver_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user_app.team')),
                ('sender_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user_app.team')),
            ],
        ),
    ]
