# Generated by Django 4.2.7 on 2023-12-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_longitude',
            field=models.FloatField(null=True),
        ),
    ]
