# Generated by Django 4.2.7 on 2023-12-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_alter_turf_amenity'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owner_app.customer'),
            preserve_default=False,
        ),
    ]
