# Generated by Django 4.2.7 on 2023-11-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='customer_phone_number',
        ),
    ]
