# Generated by Django 4.2.7 on 2023-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_skill',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='team_skill',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=20),
        ),
    ]
