# Generated by Django 4.2.7 on 2023-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_player_player_skill_team_team_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='invitation_pending',
            field=models.BooleanField(default=False),
        ),
    ]
