# Generated by Django 4.2.7 on 2023-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_team_team_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pic',
            field=models.ImageField(null=True, upload_to='player_image/'),
        ),
    ]
