# Generated by Django 4.2.7 on 2023-12-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_player_player_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_code',
        ),
    ]
