# Generated by Django 4.2.7 on 2023-12-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_player_team_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(related_name='players', to='user_app.team'),
        ),
    ]
