# Generated by Django 4.2.7 on 2023-11-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_phone_number_customer_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone_number',
            new_name='mobile',
        ),
    ]
