# Generated by Django 4.2.7 on 2023-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(related_name='teams', to='user_app.player'),
        ),
    ]
