# Generated by Django 4.2.7 on 2023-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_player_player_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pic',
            field=models.ImageField(default=1, upload_to='player_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_pic',
            field=models.ImageField(default=1, upload_to='team_image/'),
            preserve_default=False,
        ),
    ]
