# Generated by Django 4.2.7 on 2023-11-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_mobile_customer_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
