# Generated by Django 4.2.7 on 2023-12-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_matchinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinvitation',
            old_name='team2',
            new_name='receiver_team',
        ),
        migrations.RenameField(
            model_name='matchinvitation',
            old_name='team1',
            new_name='sender_team',
        ),
    ]
