# Generated by Django 4.2.7 on 2023-12-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_player_player_pic_alter_team_team_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pic',
            field=models.ImageField(null=True, upload_to='player_image/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_pic',
            field=models.ImageField(null=True, upload_to='team_image/'),
        ),
    ]
