# Generated by Django 4.2.7 on 2023-12-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_player_team_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
    ]
