# Generated by Django 4.2.7 on 2023-12-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_player_player_pic_alter_team_team_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_longitude',
            field=models.FloatField(null=True),
        ),
    ]
