# Generated by Django 4.2.7 on 2023-12-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_team2_matchinvitation_receiver_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinvitation',
            name='is_accepted',
        ),
    ]
