# Generated by Django 4.2.7 on 2023-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_matchinvitation_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinvitation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
