# Generated by Django 4.2.7 on 2023-11-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=55)),
                ('court_location', models.CharField(max_length=55)),
                ('court_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('court_image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
