# Generated by Django 4.2.7 on 2023-12-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_matchinvitation_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_longitude',
            field=models.FloatField(null=True),
        ),
    ]
