# Generated by Django 4.2.7 on 2023-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_court'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='amenity_icon/')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='court_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='court_amenity',
            field=models.ManyToManyField(to='user_app.amenity'),
        ),
    ]
