# Generated by Django 4.2.7 on 2023-12-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_player_team_player_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_player',
            field=models.ManyToManyField(related_name='team', to='user_app.player'),
        ),
    ]
