# Generated by Django 4.2.7 on 2023-11-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_amenity_court_court_description_court_court_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='court_amenity',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='Court',
        ),
    ]
