# Generated by Django 4.2.7 on 2023-12-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_team_team_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_player',
            new_name='player',
        ),
    ]
