# Generated by Django 4.2.7 on 2023-12-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_rename_team_player_team_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
    ]
