# Generated by Django 4.2.7 on 2023-11-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_turfbooking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurfBooking',
        ),
    ]
