# Generated by Django 4.2.7 on 2023-11-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=55)),
                ('player_photo', models.ImageField(upload_to='player_image/')),
                ('player_position', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=55)),
                ('team_strength', models.IntegerField()),
                ('team_longitude', models.FloatField()),
                ('team_latitude', models.FloatField()),
                ('player', models.ManyToManyField(to='user_app.player')),
            ],
        ),
    ]
