# Generated by Django 4.2.7 on 2023-11-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '__first__'),
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('date_played', models.DateField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='user_app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='user_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.matchmodel')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.turf')),
            ],
        ),
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
