# Generated by Django 4.2.7 on 2023-12-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='ai_rating',
            field=models.FloatField(null=True),
        ),
    ]
