# Generated by Django 4.2.7 on 2023-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
