# Generated by Django 4.2.7 on 2023-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
