# Generated by Django 4.2.7 on 2023-12-07 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemrewardsmodel',
            name='reward_points',
        ),
        migrations.AddField(
            model_name='redeemrewardsmodel',
            name='redeemed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
