# Generated by Django 4.2.7 on 2023-11-30 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0001_initial'),
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.customer'),
        ),
        migrations.AddField(
            model_name='turf',
            name='amenity',
            field=models.ManyToManyField(to='owner_app.amenity'),
        ),
        migrations.AddField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistorymodel',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.turf'),
        ),
        migrations.AddField(
            model_name='paymenthistorymodel',
            name='turf_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.turfbooking'),
        ),
        migrations.AddField(
            model_name='paymenthistorymodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.customer'),
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.matchmodel'),
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.turf'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='user_app.team'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='user_app.team'),
        ),
        migrations.AddField(
            model_name='owner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
