<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-20 12:31
=======
# Generated by Django 4.2.7 on 2023-12-20 09:46
>>>>>>> cbc4afa5ec419e596afcdd692c6e6e3f89b368b1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_app', '0001_initial'),
        ('user_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchratingmodel',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_match', to='user_app.team'),
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_match', to='user_app.team'),
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.turf'),
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='turf_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.turfbooking'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiturfbookmodel',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.turf'),
        ),
        migrations.AddField(
            model_name='aiturfbookmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.customer'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='turfbooking',
            unique_together={('turf', 'date', 'start_time', 'end_time')},
        ),
    ]
