# Generated by Django 4.2.7 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='amenity_icon')),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=55)),
                ('turf_location', models.CharField(max_length=55)),
                ('turf_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turf_image', models.ImageField(upload_to='image/')),
                ('turf_description', models.CharField(max_length=255)),
                ('turf_amenity', models.ManyToManyField(to='owner_app.amenity')),
            ],
        ),
    ]
