# Generated by Django 4.2.7 on 2023-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='u_id',
            field=models.IntegerField(default=0),
        ),
    ]
