# Generated by Django 4.2.7 on 2023-12-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiTurfBookModel',
        ),
    ]
