# Generated by Django 4.2.7 on 2023-12-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchratingmodel',
            name='date_played',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
