# Generated by Django 4.2.7 on 2023-12-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_alter_profile_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
