# Generated by Django 4.2.7 on 2023-11-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_amenity_turf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='turf_amenity',
            new_name='amenity',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='turf_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='turf_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='turf_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='turf_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='turf_price',
            new_name='price',
        ),
    ]
