# Generated by Django 4.2.7 on 2023-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_alter_turfbooking_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
