# Generated by Django 4.2.7 on 2023-11-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('owner_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchratingmodel',
            name='match',
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='date_played',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='team1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='user_app.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchratingmodel',
            name='team2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='user_app.team'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatchModel',
        ),
    ]
