# Generated by Django 4.2.7 on 2023-12-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_turf_ai_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='amenity',
            field=models.ManyToManyField(null=True, to='owner_app.amenity'),
        ),
    ]
