# Generated by Django 4.2.7 on 2023-12-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_remove_redeemrewardsmodel_reward_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemrewardsmodel',
            name='redeemed_at',
        ),
    ]
