# Generated by Django 4.2.7 on 2023-12-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_matchratingmodel_date_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchratingmodel',
            name='turf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owner_app.turf'),
            preserve_default=False,
        ),
    ]
