# Generated by Django 4.2.7 on 2023-12-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchratingmodel',
            name='players_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
