# Generated by Django 4.2.7 on 2023-12-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_remove_turf_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfPriceUpdateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(null=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner_app.turf')),
            ],
        ),
    ]
