# Generated by Django 4.2.7 on 2023-11-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('owner_app', '0003_remove_matchratingmodel_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchratingmodel',
            name='team2',
        ),
        migrations.AlterField(
            model_name='matchratingmodel',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.team'),
        ),
    ]
