# Generated by Django 4.2.7 on 2023-12-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_matchratingmodel_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
