# Generated by Django 4.2.7 on 2023-12-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_remove_redeemrewardsmodel_redeemed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemrewardsmodel',
            name='redeemed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
