# Generated by Django 4.2.7 on 2023-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_alter_turf_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='amenity',
            field=models.ManyToManyField(to='owner_app.amenity'),
        ),
    ]
