# Generated by Django 4.2.7 on 2023-12-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_aiturfbookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiturfbookmodel',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.turf'),
        ),
    ]
