# Generated by Django 4.2.7 on 2023-12-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0003_customer_alter_paymenthistorymodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
