# Generated by Django 4.2.7 on 2023-11-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0004_alter_owner_groups_alter_owner_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
