# Generated by Django 4.2.7 on 2023-12-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0004_aiturfbookmodel_turf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='Payment_type',
            field=models.CharField(choices=[('Partial_payment', 'Partial_payment'), ('Full_payment', 'Full_payment'), ('Offline_payment', 'Offline_payment')], default='Partial_payment', max_length=30),
        ),
    ]
