# Generated by Django 4.2.7 on 2023-12-01 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0004_customer_customer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_mobile',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
