# Generated by Django 4.2.7 on 2023-12-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0004_turfpriceupdatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfpriceupdatemodel',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turfpriceupdatemodel',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
