# Generated by Django 4.2.7 on 2023-11-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0005_rename_phone_number_owner_phone_no'),
        ('owner_app', '0005_turfbooking'),
    ]

    operations = [
    ]
