# Generated by Django 4.2.7 on 2023-12-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0005_remove_customer_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
