# Generated by Django 4.2.7 on 2023-12-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0005_alter_turfpriceupdatemodel_new_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurfPriceUpdateModel',
        ),
    ]
