# Generated by Django 4.2.7 on 2023-12-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_abstract_u_id'),
        ('owner_app', '0005_alter_turfbooking_payment_type'),
    ]

    operations = [
    ]
