# Generated by Django 4.2.7 on 2023-12-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0006_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
