# Generated by Django 4.2.7 on 2023-12-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0006_merge_20231213_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
