# Generated by Django 4.2.7 on 2023-12-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0007_alter_turf_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='u_id',
        ),
    ]
