# Generated by Django 4.2.7 on 2023-11-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0007_turf_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.turfbooking')),
            ],
        ),
    ]
