# Generated by Django 4.2.7 on 2023-11-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0008_paymenthistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistorymodel',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner_app.turf'),
        ),
    ]
