# Generated by Django 4.2.7 on 2023-12-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
    ]
