# Generated by Django 4.2.7 on 2023-11-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_customer_groups_and_more'),
        ('owner_app', '0009_paymenthistorymodel_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistorymodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.customer'),
        ),
    ]
