# Generated by Django 4.2.7 on 2023-11-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0010_paymenthistorymodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfbooking',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='turfbooking',
            name='Payment_type',
            field=models.CharField(choices=[('Partial_payment', 'Partial_payment'), ('Full_payment', 'Full_payment')], default='Partial_payment', max_length=30),
        ),
        migrations.AddField(
            model_name='turfbooking',
            name='balace',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turfbooking',
            name='partial',
            field=models.IntegerField(default=300, null=True),
        ),
    ]
