# Generated by Django 4.2.7 on 2023-11-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0011_remove_turfbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfbooking',
            old_name='balace',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='turfbooking',
            old_name='partial',
            new_name='partial_payment',
        ),
    ]
