# Generated by Django 4.2.7 on 2023-11-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0012_rename_balace_turfbooking_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfbooking',
            old_name='partial_payment',
            new_name='amount_paid',
        ),
    ]
