# Generated by Django 4.2.7 on 2023-11-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0013_rename_partial_payment_turfbooking_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfbooking',
            old_name='amount_paid',
            new_name='partial_payment',
        ),
    ]
