# Generated by Django 4.2.7 on 2023-11-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0014_rename_amount_paid_turfbooking_partial_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfbooking',
            old_name='partial_payment',
            new_name='amount_paid',
        ),
    ]
