# Generated by Django 4.2.7 on 2023-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0015_rename_partial_payment_turfbooking_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
