# Generated by Django 4.2.7 on 2023-11-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0005_turf_is_active'),
        ('owner_app', '0016_alter_turfbooking_end_time'),
    ]

    operations = [
    ]
