# Generated by Django 4.2.7 on 2023-11-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('owner_app', '0016_alter_turfbooking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='owner_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user_permissions',
            field=models.ManyToManyField(null=True, related_name='owner_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='turfbooking',
            name='end_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
