# Generated by Django 4.2.7 on 2023-11-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0016_alter_turfbooking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='end_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
