# Generated by Django 4.2.7 on 2023-11-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0017_alter_turfbooking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='turfbooking',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turfbooking',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
