# Generated by Django 4.2.7 on 2023-11-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0018_alter_turfbooking_date_alter_turfbooking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turfbooking',
            name='end_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turfbooking',
            name='start_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
